- angular/AutoComplete/multiple-columns.md
- angular/Button/Getting-Started.md
- angular/Chart/3D-Chart.md
- angular/Chart/Trendlines.md
- angular/Spreadsheet/Getting-Started.md
- angular/Spreadsheet/Rows-and-Columns.md
- angular/TreeGrid/Selection.md
Hi @ChristoIssac,
Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman
> SEO-2050_Site_Audit_Issues

- angular/Button/Custom-Buttons.md
- angular/Button/Icons.md
- angular/Diagram/Swim-lane.md
- angular/Spreadsheet/Editing.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2423_Site_Audit_Issues

- angular/Button/Miscellaneous.md
- angular/Button/RTL-Support.md
- angular/Button/Repeat-Button.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2475_Site_Audit_Issues

- angular/Button/Miscellaneous.md
- angular/Button/RTL-Support.md
- angular/Button/Repeat-Button.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2513_Site_Audit_Issues

- angular/Grid/Print-Grid.md
- angular/RichTextEditor/HowTo.md
Hi @Aishwarya-Ganesan ,
Please find changes made on angular md file.
Regards,
Scholar.
> SEO-2489 Angular Changes

- angular/Chart/Annotations.md
- angular/Chart/Appearance.md
- angular/Chart/Trendlines.md
Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 3 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/angular-docs/pull/186 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
> SEO-2684-Coverage-report-pages-with-redirect

- angular/Grid/Editing.md
|Title|Description|
|:--|:--|
|**Task Category** | Need to rename 20 image - Alt Text|
|**Content task link/ Mail screenshot** | N/A |
|**Hotfix PR link** | https://github.com/syncfusion-content/angular-docs/pull/147
|**Ticket link/Task link** | https://syncfusion.atlassian.net/browse/SEO-2705 |
|**Excel/SharePoint link** | N/A |
> SEO-2488 - Angular Grid Image Alt Text

- angular/GettingStarted/getting-started-angular-with-mvc-application.md
The images not loaded issue in EJ1 documentation has been resolved.
> (JS-64346):correction added

- angular/GettingStarted/overview.md
- angular/Overview.md
Please review changes for Permanent redirect.
Regards,
Sharly A.
> SEO-3267 - Angular Controls Permanent Redirect

- angular/DateTimePicker/Getting-Started.md
- angular/Grid/Overview.md
- angular/ReportViewer/Getting-Started.md
Hi @Aishwarya-Ganesan ,
Please review the changes for Angular Desc too long short.
Regards,
Yvone.
> SEO-3147 Angular Desc too long short

- angular/DropDownList/SettingDimension.md
- angular/Grid/ContextMenu.md
- angular/Grid/Getting-Started.md
Worked on bing report issues, so merge these changes
Regards,
Gowthaman
> SEO-3261-bing-report-issues

- angular/Chart/Chart-Dimensions.md
- angular/Grid/Stackedheader.md
Worked image image alt text.
Regards,
Sharly A.
> SEO-3353 - Angular controls image alt text

- angular/Diagram/Gridlines.md
- angular/Kanban/Swimlanes.md
- angular/Tab/Appearance-and-Styling.md
- angular/Tile/Overview.md
Hi @Aishwarya-Ganesan ,
Have changed title, description, H1 and named images.
Regards,
Yvone.
> SEO-3569 Angular Controls Site Audit

- angular/Chart/Printing.md
- angular/CircularGauge/Getting-started.md
- angular/CurrencyTextbox/RTL-Support.md
- angular/Dialog/animation.md
- angular/Dialog/appearance-and-styling.md
- angular/DropDownList/Customization.md
- angular/Splitter/Getting-Started.md
- angular/Splitter/RTL-Support.md
- angular/Toolbar/Getting-Started.md
- angular/TreeMap/Getting-started.md
Worked on Bing report issues, so merge these changes
Regards,
Gowthaman
> SEO-3615-bing-issues

- angular/Button/Overview.md
- angular/Gantt/Overview.md
Hi @Aishwarya-Ganesan ,
Have change title, description, and H1.
Regards,
Yvone.
> SEO-171762 Angular Bing reports

- angular/Menu/Context-Menu.md
Hi @gowthamanthavasiyappan ,
Have changed title, H1 and description for Angular.
Regards,
Yvone.
> SEO-172157 Angular Desc too long short

- angular/Overview.md
Kindly review angular overview changes.
Regards,
Sharly A.
> SEO-172146 - Angular Overview Semrush report

- angular/Button/Overview.md
- angular/DateTimePicker/Overview.md
- angular/Menu/Context-Menu.md
- angular/Splitter/How-To.md
Hi @MallikaRK ,
Worked on description is too long /short.
Regards,
Sharly A.
> SEO-172159 - Angular Description too long / short

- angular/Tile/Overview.md
Hi @Girija-Rajendran 
Modified multiple H1. Kindly review.
Regards,
Amy P.
> SEO - 172169 Angular Overview Multiple H1

- angular/Dialog/how-to.md
Hi. Girija-Rajendran ,
Kindly review.
Modifying the missing H1 in PR below.
Regards,
Dickson J
> SEO-172168-Angular-Dialog-control-missing-H1

- angular/GettingStarted/getting-started-with-angular-quick-start-webpack.md
- angular/GettingStarted/getting-started-with-visual-studio-environment.md
- angular/RichTextEditor/Working-with-Tables.md
- angular/Slider/Getting-Started.md
- angular/Tooltip/Getting-Started.md
- angular/TreeView/Getting-Started.md
Hello,
I have worked on the image alt text.
Regards,
Beryl.
> SEO-176113-Image-Alt-Text-Angular

- angular/Grid/Exporting.md
Hello, 
Worked on links with redirects.
Regards,
Beryl
> SEO-176113-Links-With-Redirects-Angular

- angular/Gantt/Data-Binding.md
HI @MallikaRK ,
Please review the changes.
Thanks.
Regards,
Edith.
> SEO-176496-Angular-page-with-redirect-links

- angular/GettingStarted/getting-started-angular-cli-with-electron.md
- angular/GettingStarted/getting-started-angular-cli.md
- angular/GettingStarted/getting-started-angular-with-mvc-application.md
- angular/GettingStarted/getting-started-with-angular-quick-start.md
- angular/GettingStarted/getting-started-with-dotnet-cli.md
- angular/GettingStarted/getting-started-with-dotnet-core.md
- angular/GettingStarted/getting-started-with-electron-systemjs.md
- angular/GettingStarted/getting-started-with-electron-webpack.md
- angular/GettingStarted/getting-started-with-visual-studio-environment.md
- angular/GettingStarted/getting-started-with-yeoman-generator.md
- angular/GettingStarted/overview.md
| Title | Description |
| -------- | -------- |
|**Task Link** | <ul><li>[183693](https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/183693)</li></ul> |
|**Feature description** | <ul><li>[593949](https://support.syncfusion.com/agent/tickets/593949)</li><li>The proper case for Node.js is Node.js – not Node.JS</li><li>![image](https://github.com/essential-studio/es-installmaker/assets/93127074/6ee405bf-eb6f-43d8-b1ab-aa806332acb7)</li><li>![image](https://github.com/essential-studio/es-installmaker/assets/93127074/18ee1f6e-6b38-4170-9157-c89cac1f7d73)</li></ul>|
|**Analysis and design** | <ul><li>Need to change the case in all the required places</li></ul>|
| **Solution description**   | <ul><li>Updated Node.js in Launcher</li><li>Updated Node.js in Web …
> 183693-Nodejs-case-changes

- angular/SunburstChart/Legend.md
|Title|Description|
|--|--|
|Task Category| Missing H1|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|UG PR link| UG -https://github.com/syncfusion-content/angular-docs/pull/365|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185532/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B1B4A962C-249C-46B6-88CD-E152228D7339%7D&file=Yvone.xlsx&action=default&mobileredirect=true&wdsle=0|
> SEO-185532 Angular Missing H1

- angular/Listview/Overview.md
Please review the below PR,
Title | Description
-- | --
Task Category | Missing H1 |
Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/angular-docs/pull/375|
Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187685/|
|Changes Made | Reason for change |
|-- | -- |
|Missing H1| To avoid multiple H1 and improve user experience |
Regards,
Yvone.
> SEO-187685 Angular Missing H1
